Lorem Ipsum es simplemente el manera de relleno
 de las imprentas y archivos de manera. Lorem Ipsum
  ha sido el manera de relleno estándar de las indust
  rias desde el año 1500, cuando un impresor (N. del T. per
  sona que se dedica a la imprenta) desconocido usó una galería d
  e textos y los mezcló de tal manera que logró hacer un libro de te
  xtos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó 
  como manera de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con so
